name: multibtree
description: Multi value BTree implementation for Dart
version: 0.0.2
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_docstore

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  quiver_collection: '>=1.0.0 <1.1.0'
  quiver_check: '>=1.0.0 <1.1.0'
  tuple: '>=0.4.0 <0.5.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
